# Generated by Django 2.2 on 2021-07-27 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='undefined', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FrontAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('due_time', models.DateTimeField()),
                ('repeatable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='./media/%Y/%m/%d/')),
                ('file_type', models.IntegerField(choices=[(0, 'image'), (1, 'video')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=1)),
                ('type', models.IntegerField(choices=[(0, 'teacher'), (1, 'student')], default=1)),
                ('front_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                                    to='teacherApp.FrontAccount')),
                ('my_class',
                 models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacherApp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('if_correct', models.BooleanField(default=False)),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.ChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('account',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.BackendAccount')),
                ('class_name', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.CASCADE,
                                                 to='teacherApp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestionUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_order', models.IntegerField(default=0)),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.ChoiceQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.People')),
            ],
        ),
    ]
