# Generated by Django 2.2 on 2021-07-27 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('teacherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='front_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.FrontAccount'),
        ),
        migrations.AlterField(
            model_name='people',
            name='my_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.Class'),
        ),
    ]
