# Generated by Django 2.2 on 2021-07-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherApp', '0002_auto_20210727_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='status',
            field=models.IntegerField(choices=[(0, 'owner'), (1, 'manager')], default=0),
        ),
        migrations.CreateModel(
            name='CompletionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(default='null')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.Homework')),
            ],
        ),
    ]
